name: mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^4.0.0
  bloc: ^4.0.0
  http: ^0.12.1
  equatable: ^1.1.1
  meta: ^1.1.8
  dio: ^3.0.9
  json_annotation: ^3.0.1
  flutter_staggered_grid_view: ^0.3.0
  overlay_support: ^1.0.4
  logger: ^0.9.1
  shared_preferences: ^0.5.7+3
  cached_network_image: ^2.2.0
  image_picker: ^0.6.7
  http_parser: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^5.0.0
  mockito: ^4.1.1
  pedantic_mono: any
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_native_splash: ^0.1.9
  flutter_flavorizr: ^1.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/logo/

flutter_native_splash:
  image: "assets/logo/logo.png"
  color: "dddddd"

# See doc: https://pub.dev/packages/flutter_flavorizr
flavorizr:
  instructions:
    # Prepare
    - 'assets:download'
    - 'assets:extract'

    # Android
    - 'android:androidManifest'
    - 'android:buildGradle'
    - 'android:dummyAssets'

    # Flutter
    - 'flutter:flavors'

    # iOS
    - 'ios:xcconfig'
    - 'ios:buildTargets'
    - 'ios:schema'
    - 'ios:dummyAssets'
    - 'ios:plist'

    # Cleanup
    - 'assets:clean'

    # IDE
    - 'ide:config'
  app:
    android:
      flavorDimension: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "pinko-dev"

      android:
        applicationId: "com.teame.pinko.mobile.dev"

      ios:
        bundleId: "com.teame.pinko.mobile.dev"

    staging:
      app:
        name: "pinko-staging"

      android:
        applicationId: "com.teame.pinko.mobile.staging"

      ios:
        bundleId: "com.teame.pinko.mobile.staging"

    production:
      app:
        name: "pinko"

      android:
        applicationId: "com.teame.pinko.mobile"

      ios:
        bundleId: "com.teame.pinko.mobile"
