name: flutter test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.3'
    - name: Install dependencies
      run: flutter pub get
    - name: Generate source files
      run: flutter packages pub run build_runner build
    - name: Run tests
      run: flutter test
